apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: demo-container
    image: wordpress
    env:
    - name: VERSION
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: wordpress_version
