apiVersion: v1
kind: Pod
metadata:
  name: mytesthostpath2
spec:
  containers:
    - name: testhostpath2
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: test
          mountPath: /tmp/data
  volumes:
    - name: test
      hostPath:
        path: /tmp/data
