apiVersion: v1
kind: Pod
metadata:
  name: mytesthostpath1
spec:
  containers:
    - name: testhostpath1
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: myvoltest
          mountPath: /tmp/data
  volumes:
    - name: myvoltest
      hostPath:
        path: /tmp/data
