apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: mynamespace
  labels:
    app: multi-container-app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 88
        - containerPort: 445
    - name: httpd-container
      image: httpd:latest
      command: ["/bin/sh"]
      args: ["-c", "echo 'ServerName localhost' >> /usr/local/apache2/conf/httpd.conf && sed -i 's/Listen 80/Listen 8080/' /usr/local/apache2/conf/httpd.conf && httpd-foreground"]
      ports:
        - containerPort: 8080
        - containerPort: 8443
