apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
  namespace: mynamespace
spec:
  selector:
    app: multi-container-app
  ports:
    - name: nginx-http
      protocol: TCP
      port: 88
      targetPort: 88
    - name: nginx-https
      protocol: TCP
      port: 445
      targetPort: 44
    - name: httpd-http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: httpd-https
      protocol: TCP
