apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2-container
        image: satyadocckerhub/myapp2:latest
        ports:
        - containerPort: 8080
