apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: mynamespace
spec:
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80 #service port clint call this port
      targetPort: 80 #container port internally routed to pod
  type: NodePort
