apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-user
spec:
  containers:
  - name: demo-container1
    image: nginx
    volumeMounts:
    - name: config
      mountPath: /etc/config
      env:
        - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: config
          key: user-name1
    - name: PASSWORD
      valueFrom:
        configMapKeyRef:
          name: config
          key: password
  volumes:
