apiVersion: v1
kind: Pod
metadata:
  name: configmap-user-demo
spec:
  containers:
    - name: user-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: username1
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: password1
